package com.twohands.authservice.infrastructure.security;

import com.twohands.authservice.application.auth.port.RefreshTokenGenerator;
import org.springframework.stereotype.Component;

import java.security.SecureRandom;
import java.util.Base64;

@Component
public class SecureRandomTokenGenerator implements RefreshTokenGenerator {

    // Initialize a cryptographically strong random number generator to ensure token unpredictability.
    // Khởi tạo một bộ sinh số ngẫu nhiên an toàn mã hóa để đảm bảo token không thể bị đoán trước.
    private static final SecureRandom SECURE_RANDOM = new SecureRandom();
    
    // Define the token size as 32 bytes (256 bits), which provides a high level of security entropy.
    // Define kích thước token là 32 bytes (256 bits), cung cấp mức độ entropy bảo mật cực cao.
    private static final int TOKEN_BYTES = 32; // 256 bits → 43-char Base64URL string

    // Override the generation method to implement the secure token creation logic.
    // Override method generation để triển khai logic tạo secure token.
    @Override
    public String generate() {
        
        // Allocate an empty byte array buffer with the predefined token length.
        // Allocate một mảng byte buffer trống với độ dài token đã được define trước đó.
        byte[] bytes = new byte[TOKEN_BYTES];
        
        // Populate the byte array with highly secure, pseudo-random generated bytes.
        // Populate mảng byte bằng các byte ngẫu nhiên (pseudo-random) có độ bảo mật cao.
        SECURE_RANDOM.nextBytes(bytes);
        
        // Encode the binary data into a URL-safe Base64 string and strip the padding '=' to keep it clean.
        // Encode dữ liệu binary sang chuỗi Base64 URL-safe và cắt bỏ phần padding '=' để token gọn gàng hơn.
        return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
    }
}
